# $NetBSD$
#

DISTNAME=	skyeye-1-3-1_rc1
CATEGORIES=	emulators
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=skyeye/}

MAINTAINER=	ryo_on@yk.rim.or.jp
HOMEPAGE=	http://www.skyeye.org/
COMMENT=	SkyEye is an Open Source Software ARM board emulator
#LICENSE=	# TODO: (see mk/license.mk)

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=	yes
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
