# $NetBSD$
#

DISTNAME=	softgun-0.19
CATEGORIES=	emulators
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=softgun/}
EXTRACT_SUFX=	.tgz

MAINTAINER=	ryo_on@yk.rim.or.jp
HOMEPAGE=	http://softgun.sourceforge.net/
COMMENT=	Softgun is an ARM (and other CPU) emulator
#LICENSE=	# TODO: (see mk/license.mk)

PKG_DESTDIR_SUPPORT=	user-destdir

USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
